pipeline {
    agent any

    environment {
        NETWORK_NAME = 'cifertech-network'
    }

    stages {
        stage('Prepare Network') {
            steps {
                echo "Verifing network"
                sh "docker network create ${NETWORK_NAME} || true"
            }
        }

         stage('Build') {
            steps {
                echo "Verifing network"
                sh "docker compose build"
            }
        }

        stage('Run proxy') {
            steps {
                
                    echo 'Starting the proxy container and the internal network'
                    sh 'docker compose up -d'
            }
        }
    }
    
}